<?php

/**
* @file
* This is the module to create error pages.
*/

/**
 * Implements hook_preprocess_breadcrumb().
 */
function university_error_pages_preprocess_breadcrumb(&$variables) {
  if (Drupal::service('current_route_match')
      ->getRouteName() == 'university_error_pages.index') {
    $variables['#cache']['tags'][] = \Drupal::config('university_error_pages.admin_config')
      ->getCacheTags()[0];
  }
}
